name: "Test & Release"

on:
  push:
    branches:
      - '*'
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test
      run: go test -v ./...

  release:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Build
      run: go build -v ./...
      
    - name: Attach Linux binary to GitHub release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/interline-healthcheck
        asset_name: interline-healthcheck
        asset_content_type: application/binary

